server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 25m;

    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "healthy\n";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
