import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { errorMessage } from "../../../utils/errorMessage";
import { Box, Boxes, Check, Circle, FileUp, RefreshCw, Upload } from "lucide-react";
import toast from "react-hot-toast";
import { useParams, useSearchParams } from "react-router-dom";

import { Badge } from "../../../components/ui/Badge";
import { Button } from "../../../components/ui/Button";
import { Card } from "../../../components/ui/Card";
import { Input } from "../../../components/ui/Input";
import { useRole } from "../../../hooks/useRole";
import api from "../../../services/api";
import type { IFCElement, IFCFinding, IFCModelGroup, IFCSpatialNode, IFCVersion } from "../../../types/ifc";
import { CompareTab, FindingsTab, SuggestionsTab } from "../components/IFCActionTabs";
import { ElementsTab } from "../components/IFCElementsTab";
import { DisciplinesTab, GeoreferencingTab, HierarchyTab, NoVersionState, OverviewTab, PropertiesQuantitiesTab, TechnicalDataTab, ViewerTab } from "../components/IFCInformationTabs";
import { EmptyState, ErrorState, IFCTabErrorBoundary, labelize, LoadingState } from "../components/IFCShared";
import { useProjectWorkspace } from "../../projects/context/ProjectWorkspaceContext";

type Tab = "overview" | "hierarchy" | "elements" | "disciplines" | "properties" | "georeferencing" | "viewer" | "compare" | "findings" | "suggestions" | "technical";
const tabs: Array<{ id: Tab; label: string; advanced?: boolean }> = [
  { id: "overview", label: "Overview" }, { id: "hierarchy", label: "Model Hierarchy" }, { id: "elements", label: "Elements" },
  { id: "disciplines", label: "Disciplines" }, { id: "properties", label: "Properties and Quantities" }, { id: "georeferencing", label: "Georeferencing" },
  { id: "viewer", label: "3D Viewer" }, { id: "compare", label: "Compare Revisions" }, { id: "findings", label: "Findings" },
  { id: "suggestions", label: "Suggestions" }, { id: "technical", label: "Technical Data", advanced: true },
];
const defaultStages = [
  { key: "upload", label: "Uploading file", percentage: 5 }, { key: "validation", label: "Validating IFC", percentage: 10 },
  { key: "schema", label: "Reading IFC schema", percentage: 20 }, { key: "hierarchy", label: "Extracting model hierarchy", percentage: 38 },
  { key: "elements", label: "Extracting elements", percentage: 52 }, { key: "properties", label: "Extracting properties and quantities", percentage: 68 },
  { key: "quality", label: "Running model-quality checks", percentage: 82 }, { key: "summary", label: "Generating intelligence summary", percentage: 92 },
  { key: "complete", label: "Completed", percentage: 100 },
];
const statusTone = (value: string) => value === "READY" ? "success" : value === "FAILED" ? "danger" : value.includes("WARNING") ? "warning" : "info";
const requestMessage = (error: unknown) => errorMessage(error, "The IFC operation could not be completed.");
const ready = (version?: IFCVersion) => Boolean(version && ["READY", "READY_WITH_WARNINGS"].includes(version.processingStatus));

export const IFCWorkspacePage = () => {
  const { t } = useTranslation();
  const workspace = useProjectWorkspace(); const params = useParams<{ projectId?: string }>(); const { role, isConsultantEngineer } = useRole();
  const [searchParams] = useSearchParams();
  const projectId = workspace.projectId || params.projectId;
  const canUpload = role === "admin" || role === "project_manager" || (role === "engineer" && !isConsultantEngineer);
  const canReviewSuggestions = role === "admin" || role === "project_manager" || role === "engineer"; const canApplySuggestions = role === "project_manager";
  const [models, setModels] = useState<IFCModelGroup[]>([]); const [modelId, setModelId] = useState(""); const [versions, setVersions] = useState<IFCVersion[]>([]); const [versionId, setVersionId] = useState("");
  const [nodes, setNodes] = useState<IFCSpatialNode[]>([]); const [elements, setElements] = useState<IFCElement[]>([]); const [elementTotal, setElementTotal] = useState(0); const [findings, setFindings] = useState<IFCFinding[]>([]);
  const [tab, setTab] = useState<Tab>("overview"); const [affectedElementIds, setAffectedElementIds] = useState<string[]>([]);
  const [viewerFocus, setViewerFocus] = useState<{elementIds?:string[];nodeId?:string}>({});
  const [loadingModels, setLoadingModels] = useState(true); const [loadingCore, setLoadingCore] = useState(false); const [modelsError, setModelsError] = useState(""); const [nodesError, setNodesError] = useState(""); const [elementsError, setElementsError] = useState("");
  const [busy, setBusy] = useState(false); const [newName, setNewName] = useState(""); const [uploadProgress, setUploadProgress] = useState<number>();
  const [upload, setUpload] = useState<{ file?: File; title: string; revision: string; versionType: string }>({ title: "", revision: "", versionType: "DESIGN" });

  const loadModels = useCallback(async () => { if (!projectId) return; setLoadingModels(true); setModelsError(""); try { const values = await api.ifc.models(projectId); setModels(values); setModelId((current) => current && values.some((item) => item.id === current) ? current : values[0]?.id || ""); } catch (error) { console.error("[IFC Intelligence] model groups failed", error); setModelsError(requestMessage(error)); } finally { setLoadingModels(false); } }, [projectId]);
  const loadVersions = useCallback(async () => { if (!projectId || !modelId) { setVersions([]); setVersionId(""); return; } try { const values = await api.ifc.versions(projectId, modelId); setVersions(values); setVersionId((current) => current && values.some((item) => item.id === current) ? current : values.find((item) => item.isActive)?.id || values[0]?.id || ""); } catch (error) { toast.error(requestMessage(error)); } }, [modelId, projectId]);
  useEffect(() => { void loadModels(); }, [loadModels]); useEffect(() => { void loadVersions(); }, [loadVersions]);

  const current = versions.find((item) => item.id === versionId); const currentModel = models.find((item) => item.id === modelId);
  useEffect(() => { if (!projectId || !current || ready(current) || current.processingStatus === "FAILED") return; const timer = window.setInterval(() => { void api.ifc.version(projectId, current.id).then((updated) => setVersions((values) => values.map((item) => item.id === updated.id ? updated : item))).catch((error) => console.error("[IFC Intelligence] processing poll failed", error)); }, 2000); return () => window.clearInterval(timer); }, [current, projectId]);
  const loadCore = useCallback(async () => { if (!projectId || !versionId || !ready(current)) { setNodes([]); setElements([]); setFindings([]); return; } setLoadingCore(true); setNodesError(""); setElementsError(""); const [tree, page, quality] = await Promise.allSettled([api.ifc.hierarchy(projectId, versionId), api.ifc.elements(projectId, versionId, { pageSize: 200 }), api.ifc.findings(projectId)]); if (tree.status === "fulfilled") setNodes(tree.value); else { console.error("[IFC Intelligence:Hierarchy] loading failed", tree.reason); setNodesError(requestMessage(tree.reason)); } if (page.status === "fulfilled") { setElements(page.value.items); setElementTotal(page.value.total); } else { console.error("[IFC Intelligence:Elements] summary loading failed", page.reason); setElementsError(requestMessage(page.reason)); } if (quality.status === "fulfilled") setFindings(quality.value.filter((item) => item.versionId === versionId)); else console.error("[IFC Intelligence:Findings] preload failed", quality.reason); setLoadingCore(false); }, [current, projectId, versionId]);
  useEffect(() => { void loadCore(); }, [loadCore]);
  useEffect(()=>{const requested=searchParams.get("tab") as Tab|null;if(requested&&tabs.some(item=>item.id===requested))setTab(requested);const elementIds=(searchParams.get("elementIds")||"").split(",").filter(Boolean);const nodeId=searchParams.get("nodeId")||undefined;if(elementIds.length||nodeId)setViewerFocus({elementIds,nodeId});},[searchParams]);

  const createGroup = async () => { if (!projectId || !newName.trim()) return; setBusy(true); try { const item = await api.ifc.createModel(projectId, { name: newName.trim() }); setNewName(""); await loadModels(); setModelId(item.id); toast.success("Model Group created"); } catch (error) { toast.error(requestMessage(error)); } finally { setBusy(false); } };
  const uploadVersion = async () => { if (!projectId || !modelId || !upload.file || !upload.title.trim() || !upload.revision.trim()) return; setBusy(true); setUploadProgress(0); try { const item = await api.ifc.uploadVersion(projectId, modelId, upload.file, { title: upload.title, revisionCode: upload.revision, versionType: upload.versionType }, setUploadProgress); setUpload({ title: "", revision: "", versionType: "DESIGN" }); await loadVersions(); setVersionId(item.id); toast.success("IFC uploaded. Processing has started."); } catch (error) { toast.error(requestMessage(error)); } finally { setBusy(false); window.setTimeout(() => setUploadProgress(undefined), 800); } };
  const retryProcessing = async () => { if (!projectId || !current) return; setBusy(true); try { await api.ifc.retryVersion(projectId, current.id); await loadVersions(); toast.success("IFC processing was queued again"); } catch (error) { toast.error(requestMessage(error)); } finally { setBusy(false); } };
  const viewElements = (ids: string[]) => { setAffectedElementIds(ids); setTab("elements"); };
  const focus3D = (elementIds:string[]=[],nodeId?:string) => { setViewerFocus({elementIds,nodeId}); setTab("viewer"); };
  const disciplineCount = Object.values(current?.modelSummaryJson?.disciplineBreakdown || {}).filter((value) => value > 0).length;
  const stages = current?.modelSummaryJson?.processingStages || defaultStages; const shownProgress = uploadProgress ?? current?.processingProgress ?? 0;

  if (!projectId) return <Card>{t("ifcWorkspace.select_a_project_to_open_ifc")}</Card>;
  return <div className="page-container space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Boxes className="text-primary"/> IFC Intelligence</h1><p className="mt-1 text-sm text-muted-foreground">Readable model facts, data-quality checks and revision intelligence for engineering teams.</p></div><div className="flex flex-wrap gap-2"><select aria-label={t("ifcWorkspace.model_group")} className="rounded-md border bg-background px-3 py-2 text-sm" value={modelId} onChange={(event) => setModelId(event.target.value)}><option value="">{t("ifcWorkspace.select_model_group")}</option>{models.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label={t("ifcWorkspace.model_revision")} className="rounded-md border bg-background px-3 py-2 text-sm" value={versionId} onChange={(event) => setVersionId(event.target.value)}><option value="">{t("ifcWorkspace.select_revision")}</option>{versions.map((item) => <option key={item.id} value={item.id}>v{item.versionNumber} · {item.revisionCode || item.title} · {labelize(item.processingStatus)}</option>)}</select></div></div>

    {canUpload && <Card><h2 className="flex items-center gap-2 font-semibold"><FileUp size={18}/> Upload IFC revision</h2><p className="mt-1 text-sm text-muted-foreground">Create or select a Model Group, choose the version type, enter the revision, then upload an .ifc file.</p><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto_1fr_1fr_1fr_auto]"><Input label={t("ifcWorkspace.new_model_group")} value={newName} onChange={(event) => setNewName(event.target.value)} placeholder={t("ifcWorkspace.architectural_model")}/><Button className="self-end" variant="outline" disabled={!newName.trim() || busy} onClick={() => void createGroup()}>{t("ifcWorkspace.create_group")}</Button><select aria-label={t("ifcWorkspace.version_type")} className="self-end rounded-md border bg-background px-3 py-2 text-sm" value={upload.versionType} onChange={(event) => setUpload((value) => ({ ...value, versionType: event.target.value }))}><option value="DESIGN">{t("ifcWorkspace.design")}</option><option value="COORDINATION">{t("ifcWorkspace.coordination")}</option><option value="CONSTRUCTION">{t("ifcWorkspace.construction")}</option><option value="AS_BUILT">{t("ifcWorkspace.as_built")}</option><option value="REFERENCE">{t("ifcWorkspace.reference")}</option></select><Input label={t("ifcWorkspace.version_title")} value={upload.title} onChange={(event) => setUpload((value) => ({ ...value, title: event.target.value }))} placeholder={t("ifcWorkspace.issued_for_coordination")}/><Input label={t("ifcWorkspace.revision_identifier")} value={upload.revision} onChange={(event) => setUpload((value) => ({ ...value, revision: event.target.value }))} placeholder="P03"/><div className="self-end space-y-2"><input aria-label={t("ifcWorkspace.ifc_file")} type="file" accept=".ifc" className="block max-w-52 text-xs" onChange={(event) => setUpload((value) => ({ ...value, file: event.target.files?.[0] }))}/><Button disabled={!modelId || !upload.file || !upload.title.trim() || !upload.revision.trim() || busy} onClick={() => void uploadVersion()}><Upload size={15}/> Upload IFC</Button></div></div></Card>}

    {loadingModels ? <LoadingState label={t("ifcWorkspace.loading_ifc_model_groups")}/> : modelsError ? <ErrorState message={modelsError} onRetry={() => void loadModels()}/> : !models.length ? <EmptyState title={t("ifcWorkspace.no_ifc_models_yet")} description="Create a Model Group, then upload an IFC2X3, IFC4 or IFC4X3 file." action={<Box className="mx-auto text-muted-foreground"/>}/> : !current ? <NoVersionState/> : <>
      <Card className={current.processingStatus === "FAILED" ? "border-red-300" : ""}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{t("ifcWorkspace.model_processing")}</h2><p className="text-sm text-muted-foreground">{current.processingStatus === "FAILED" ? current.parsingErrorMessage || "Parsing or extraction failed. No successful result has been reported." : ready(current) ? "Processing completed and model intelligence is ready." : stages.findLast((stage) => shownProgress >= stage.percentage)?.label || "Validating IFC"}</p></div><div className="flex items-center gap-3"><Badge variant={statusTone(current.processingStatus)}>{labelize(current.processingStatus)}</Badge><b className="text-xl">{shownProgress}%</b>{current.processingStatus === "FAILED" && <Button variant="outline" size="sm" disabled={busy} onClick={() => void retryProcessing()}><RefreshCw size={15}/> Retry</Button>}</div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-muted"><div className={`h-full transition-all ${current.processingStatus === "FAILED" ? "bg-red-500" : "bg-primary"}`} style={{ width: `${Math.min(100, shownProgress)}%` }}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{stages.map((stage) => { const complete = ready(current) || (current.processingStatus !== "FAILED" && shownProgress >= stage.percentage); return <div key={stage.key} className={`flex items-center gap-2 rounded-lg border p-2 text-xs ${complete ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "text-muted-foreground"}`}>{complete ? <Check size={14}/> : <Circle size={12}/>} {stage.label}</div>; })}</div></Card>
      {ready(current) && <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{currentModel?.name} · {labelize(current.versionType)}</p><h2 className="mt-1 text-xl font-bold">{current.title}</h2><p className="text-sm text-muted-foreground">Revision {current.revisionCode || `v${current.versionNumber}`} · {current.entityCount.toLocaleString()} extracted elements · {disciplineCount} disciplines detected</p></div><div className="flex gap-2"><Button size="sm" onClick={() => setTab("viewer")}>{t("ifcWorkspace.view_3d")}</Button><Button size="sm" variant="outline" onClick={() => setTab("compare")}>{t("ifcWorkspace.compare_revision")}</Button><Button size="sm" variant="outline" onClick={() => setTab("technical")}>{t("ifcWorkspace.technical_information")}</Button></div></div></Card>}
      <div className="flex overflow-x-auto border-b">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${tab === item.id ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>{item.label}{item.advanced && <small className="ml-1">· Advanced</small>}</button>)}</div>
      {!ready(current) ? current.processingStatus === "FAILED" ? <ErrorState message={current.parsingErrorMessage || "The IFC model could not be parsed or extracted."} onRetry={() => void retryProcessing()}/> : <LoadingState label={t("ifcWorkspace.model_analysis_will_appear_here_when")}/> : loadingCore ? <LoadingState/> : <IFCTabErrorBoundary name={tab} onRetry={() => void loadCore()}>
        {tab === "overview" && <OverviewTab version={current}/>} {tab === "hierarchy" && (nodesError ? <ErrorState message={nodesError} onRetry={() => void loadCore()}/> : <HierarchyTab projectId={projectId} nodes={nodes} onViewElements={viewElements} onFocus3D={(nodeId,ids)=>focus3D(ids,nodeId)}/>)}
        {tab === "elements" && (elementsError ? <ErrorState message={elementsError} onRetry={() => void loadCore()}/> : <ElementsTab projectId={projectId} versionId={versionId} nodes={nodes} findings={findings} initialElementIds={affectedElementIds} onFocus3D={(id)=>focus3D([id])}/>)}
        {tab === "disciplines" && <DisciplinesTab elements={elements} summary={current.modelSummaryJson}/>} {tab === "properties" && <PropertiesQuantitiesTab elements={elements} total={elementTotal}/>} {tab === "georeferencing" && <GeoreferencingTab summary={current.modelSummaryJson}/>} {tab === "viewer" && <ViewerTab projectId={projectId} version={current} nodes={nodes} focus={viewerFocus}/>} {tab === "compare" && <CompareTab projectId={projectId} versions={versions} currentVersionId={versionId}/>} {tab === "findings" && <FindingsTab projectId={projectId} versionId={versionId} onViewElements={viewElements}/>} {tab === "suggestions" && <SuggestionsTab projectId={projectId} versionId={versionId} canReview={canReviewSuggestions} canApply={canApplySuggestions} onViewElements={viewElements}/>} {tab === "technical" && <TechnicalDataTab version={current} nodes={nodes} elements={elements}/>} 
      </IFCTabErrorBoundary>}
    </>}
  </div>;
};
