"""Announcing that something changed — and nothing more than that.

The single rule this module exists to enforce: **an event is a hint, never
state.** It carries identifiers and a type, so a client knows *what* to
re-read; it never carries a message body, a document, a cost, or a name. Two
reasons, and the second is the one that matters:

  * The database stays the source of truth. A client that refetches through the
    existing REST endpoints gets data that has already passed every
    authorization check those endpoints apply.
  * Authorization on the stream is therefore defence in depth rather than the
    only line. If the per-connection filter in `broker.py` ever has a bug, it
    leaks an *identifier* — not the contents of somebody else's contract.

Delivery is `pg_notify` on the caller's own session, which makes it
transactional: PostgreSQL holds the notification until the surrounding
transaction commits and discards it on rollback. So an event cannot announce a
change that never happened, and this needs no `after_commit` hook of its own —
the database provides the guarantee that `app.services.push` had to build.
"""

from __future__ import annotations

import json
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.core.config import settings

logger = logging.getLogger("uvicorn.error").getChild("realtime.publish")

#: The one PostgreSQL channel every worker listens on. A single channel with
#: type-based filtering beats a channel per event type: `LISTEN` is per
#: connection, and a channel per type would multiply connections for no gain.
CHANNEL = "realtime"

#: PostgreSQL refuses a NOTIFY payload above 8000 bytes. Envelopes are two
#: orders of magnitude smaller, so this is a guard against a future field
#: quietly growing, not an expected condition.
MAX_PAYLOAD_BYTES = 7000


class EventType:
    """The events the frontend knows how to react to.

    Deliberately few. Every type here has a subscriber; speculative types are
    worse than absent ones because they look supported and are not.
    """

    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    NOTIFICATION_UPDATED = "NOTIFICATION_UPDATED"
    MESSAGE_CREATED = "MESSAGE_CREATED"
    MESSAGE_UPDATED = "MESSAGE_UPDATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    ISSUE_CREATED = "ISSUE_CREATED"
    ISSUE_UPDATED = "ISSUE_UPDATED"
    #: Synthetic, generated by the client on (re)connect — never published by
    #: the server. Named here so both sides share one vocabulary.
    REALTIME_RECONNECTED = "REALTIME_RECONNECTED"


ALL_EVENT_TYPES = frozenset(
    value
    for key, value in vars(EventType).items()
    if not key.startswith("_") and isinstance(value, str)
)


@dataclass(frozen=True)
class RealtimeEvent:
    """One "something changed" hint.

    Exactly one of `user_id` / `project_id` decides who may see it:

      * `user_id` set   — targeted at one person (their notification).
      * `project_id` set — anyone who can access that project.

    Both may be set: a notification that also belongs to a project. Neither
    being set is rejected at publish time, because an event nobody can be
    authorized for would either reach everyone or nobody, and both are bugs.
    """

    type: str
    project_id: uuid.UUID | None = None
    user_id: uuid.UUID | None = None
    entity_type: str | None = None
    entity_id: uuid.UUID | None = None
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    ts: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_payload(self) -> dict[str, Any]:
        payload: dict[str, Any] = {"id": self.id, "type": self.type, "ts": self.ts}
        if self.project_id:
            payload["projectId"] = str(self.project_id)
        if self.user_id:
            payload["userId"] = str(self.user_id)
        if self.entity_type:
            payload["entityType"] = self.entity_type
        if self.entity_id:
            payload["entityId"] = str(self.entity_id)
        return payload

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "RealtimeEvent":
        def as_uuid(value):
            return uuid.UUID(value) if value else None

        return cls(
            id=payload.get("id") or uuid.uuid4().hex,
            type=payload["type"],
            ts=payload.get("ts") or datetime.now(timezone.utc).isoformat(),
            project_id=as_uuid(payload.get("projectId")),
            user_id=as_uuid(payload.get("userId")),
            entity_type=payload.get("entityType"),
            entity_id=as_uuid(payload.get("entityId")),
        )


def publish(db: Session, event: RealtimeEvent) -> bool:
    """Queue an event for delivery when the caller's transaction commits.

    Returns False when the event was not queued. Never raises: realtime is an
    enhancement, and a failure here must not roll back the business write that
    triggered it. That asymmetry is the whole reason this returns a bool
    instead of throwing.
    """
    if not settings.REALTIME_ENABLED:
        return False
    if event.user_id is None and event.project_id is None:
        # Unaddressable: no filter could decide who should receive it.
        logger.warning("refusing to publish %s with neither userId nor projectId", event.type)
        return False

    payload = json.dumps(event.to_payload(), separators=(",", ":"))
    if len(payload.encode("utf-8")) > MAX_PAYLOAD_BYTES:
        logger.error("refusing to publish oversized %s event (%s bytes)", event.type, len(payload))
        return False

    try:
        # On the caller's session on purpose: PostgreSQL delivers a NOTIFY only
        # if its transaction commits, so a rolled-back write announces nothing.
        db.execute(text("SELECT pg_notify(:channel, :payload)"), {"channel": CHANNEL, "payload": payload})
    except Exception:
        # Logged, not raised — see the docstring.
        logger.exception("could not publish realtime event %s", event.type)
        return False

    logger.debug("published %s (%s)", event.type, event.id)
    return True


def publish_event(
    db: Session,
    *,
    event_type: str,
    project_id: uuid.UUID | None = None,
    user_id: uuid.UUID | None = None,
    entity_type: str | None = None,
    entity_id: uuid.UUID | None = None,
) -> bool:
    """Keyword-argument convenience wrapper. The form call sites should use."""
    return publish(
        db,
        RealtimeEvent(
            type=event_type,
            project_id=project_id,
            user_id=user_id,
            entity_type=entity_type,
            entity_id=entity_id,
        ),
    )
