"""add_enterprise_auth_fields

Revision ID: e3fd29975a61
Revises: b2ac9f00788a
Create Date: 2026-06-27 09:47:29.634314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fd29975a61'
down_revision: Union[str, None] = 'b2ac9f00788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineer_profiles', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('invitation_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('organization', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization')
    op.drop_column('users', 'invitation_accepted')
    op.drop_column('users', 'must_change_password')
    op.drop_column('engineer_profiles', 'employee_id')
    # ### end Alembic commands ###
