export const ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  CHANGE_PASSWORD: "/auth/change-password",
  DASHBOARD: "/dashboard",
  PROJECTS: "/projects",
  PM_PROJECTS: "/project-manager/projects",
  PM_PROJECT_DASHBOARD: "/project-manager/projects/:id/dashboard",
  PM_PROJECT_TASKS: "/project-manager/projects/:projectId/tasks",
  PM_PROJECT_TASK_DETAIL: "/project-manager/projects/:projectId/tasks/:taskId",
  PM_PROJECT_DOCUMENTS: "/project-manager/projects/:projectId/documents",
  PM_PROJECT_SITE_REPORTS: "/project-manager/projects/:projectId/site-reports",
  PM_PROJECT_ISSUES: "/project-manager/projects/:projectId/issues",
  PM_PROJECT_DESIGN_CHANGES: "/project-manager/projects/:projectId/design-changes",
  PM_PROJECT_TEAM: "/project-manager/projects/:projectId/team",
  PM_PROJECT_SCHEDULE: "/project-manager/projects/:projectId/schedule",
  PM_PROJECT_MILESTONES: "/project-manager/projects/:projectId/milestones",
  PM_PROJECT_MESSAGES: "/project-manager/projects/:projectId/messages",
  PM_PROJECT_NOTIFICATIONS: "/project-manager/projects/:projectId/notifications",
  PM_PROJECT_EVIDENCE: "/project-manager/projects/:projectId/evidence",
  PM_PROJECT_IFC: "/project-manager/projects/:projectId/ifc",
  PM_PROJECT_AI_INTELLIGENCE: "/project-manager/projects/:projectId/ai-intelligence",
  PM_PROJECT_COLLABORATION: "/project-manager/projects/:projectId/collaboration",
  PM_PROJECT_REQUESTS: "/project-manager/projects/:projectId/requests",
  PM_PROJECT_SITE_VISITS: "/project-manager/projects/:projectId/site-visits",
  PM_PROJECT_ACTIVITY: "/project-manager/projects/:projectId/activity",
  ENGINEER_PROJECTS: "/engineer/projects",
  ENGINEER_PROJECT_DASHBOARD: "/engineer/projects/:projectId/dashboard",
  ENGINEER_PROJECT_TASKS: "/engineer/projects/:projectId/tasks",
  ENGINEER_PROJECT_TASK_DETAIL: "/engineer/projects/:projectId/tasks/:taskId",
  ENGINEER_PROJECT_SITE_REPORTS: "/engineer/projects/:projectId/site-reports",
  ENGINEER_PROJECT_ISSUES: "/engineer/projects/:projectId/issues",
  ENGINEER_PROJECT_DOCUMENTS: "/engineer/projects/:projectId/documents",
  ENGINEER_PROJECT_NOTIFICATIONS: "/engineer/projects/:projectId/notifications",
  ENGINEER_PROJECT_EVIDENCE: "/engineer/projects/:projectId/evidence",
  ENGINEER_PROJECT_VOICE_REPORTS: "/engineer/projects/:projectId/voice-reports",
  ENGINEER_PROJECT_IFC: "/engineer/projects/:projectId/ifc",
  ENGINEER_PROJECT_AI_INTELLIGENCE: "/engineer/projects/:projectId/ai-intelligence",
  ENGINEER_PROJECT_MESSAGES: "/engineer/projects/:projectId/messages",
  ENGINEER_PROJECT_COLLABORATION: "/engineer/projects/:projectId/collaboration",
  ENGINEER_PROJECT_REQUESTS: "/engineer/projects/:projectId/requests",
  ENGINEER_PROJECT_SITE_VISITS: "/engineer/projects/:projectId/site-visits",
  ENGINEER_PROJECT_ACTIVITY: "/engineer/projects/:projectId/activity",
  CONSULTANT_PROJECTS: "/consultant-engineer/projects",
  CONSULTANT_PROJECT_DASHBOARD: "/consultant-engineer/projects/:projectId/dashboard",
  CONSULTANT_PENDING_REVIEWS: "/consultant-engineer/projects/:projectId/reviews",
  CONSULTANT_REVIEW_DETAIL: "/consultant-engineer/projects/:projectId/reviews/:reviewId",
  CONSULTANT_REVIEW_HISTORY: "/consultant-engineer/projects/:projectId/history",
  CONSULTANT_PROJECT_DOCUMENTS: "/consultant-engineer/projects/:projectId/documents",
  CONSULTANT_PROJECT_SITE_REPORTS: "/consultant-engineer/projects/:projectId/site-reports",
  CONSULTANT_PROJECT_ISSUES: "/consultant-engineer/projects/:projectId/issues",
  CONSULTANT_PROJECT_DESIGN_CHANGES: "/consultant-engineer/projects/:projectId/design-changes",
  CONSULTANT_PROJECT_NOTIFICATIONS: "/consultant-engineer/projects/:projectId/notifications",
  CONSULTANT_PROJECT_EVIDENCE: "/consultant-engineer/projects/:projectId/evidence",
  CONSULTANT_PROJECT_IFC: "/consultant-engineer/projects/:projectId/ifc",
  CONSULTANT_PROJECT_AI_INTELLIGENCE: "/consultant-engineer/projects/:projectId/ai-intelligence",
  CONSULTANT_PROJECT_MESSAGES: "/consultant-engineer/projects/:projectId/messages",
  CONSULTANT_PROJECT_COLLABORATION: "/consultant-engineer/projects/:projectId/collaboration",
  CONSULTANT_PROJECT_REQUESTS: "/consultant-engineer/projects/:projectId/requests",
  CONSULTANT_PROJECT_SITE_VISITS: "/consultant-engineer/projects/:projectId/site-visits",
  CONSULTANT_PROJECT_ACTIVITY: "/consultant-engineer/projects/:projectId/activity",
  PROJECT_DASHBOARD: "/projects/:projectId/dashboard",
  PROJECT_TASKS: "/projects/:projectId/tasks",
  PROJECT_TASK_DETAIL: "/projects/:projectId/tasks/:taskId",
  PROJECT_DOCUMENTS: "/projects/:projectId/documents",
  PROJECT_SITE_REPORTS: "/projects/:projectId/site-reports",
  PROJECT_ISSUES: "/projects/:projectId/issues",
  PROJECT_DESIGN_CHANGES: "/projects/:projectId/design-changes",
  PROJECT_TEAM: "/projects/:projectId/team",
  PROJECT_MESSAGES: "/projects/:projectId/messages",
  PROJECT_REQUESTS: "/projects/:projectId/requests",
  PROJECT_SITE_VISITS: "/projects/:projectId/site-visits",
  PROJECT_ACTIVITY: "/projects/:projectId/activity",
  PROJECT_EVIDENCE: "/projects/:projectId/evidence",
  PROJECT_IFC: "/projects/:projectId/ifc",
  PROJECT_AI_INTELLIGENCE: "/projects/:projectId/ai-intelligence",
  PROJECT_DETAIL: "/projects/:id",
  PROJECT_SCHEDULE: "/projects/:id/schedule",
  PROJECT_MILESTONES: "/projects/:projectId/milestones",
  TEAM: "/team",
  TASKS: "/tasks",
  TASK_DETAIL: "/tasks/:id",
  DOCUMENTS: "/documents",
  REPORTS: "/reports",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  USERS: "/users",
  SETTINGS: "/settings",
  OWNER_DASHBOARD: "/owner-dashboard",
  EXECUTIVE_OVERVIEW: "/executive-overview",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_TEAMS: "/admin/project-teams",
  ADMIN_PROJECT_TEAM: "/admin/projects/:projectId/team",
  ISSUES: "/issues",
  DESIGN_CHANGES: "/design-changes",
  SITE_REPORTS: "/site-reports",
  MY_ACTIONS: "/my-actions",
  REQUESTS: "/requests",
  SCHEDULE: "/schedule",
  PROJECT_COLLABORATION: "/projects/:projectId/collaboration",
  NOT_FOUND: "*",
} as const;

/* ─── Date format strings (date-fns compatible) ─── */
export const DATE_FORMAT = "yyyy-MM-dd";
export const DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
export const DISPLAY_DATE_FORMAT = "dd MMM yyyy";
export const DISPLAY_DATE_TIME_FORMAT = "dd MMM yyyy, HH:mm";

/* ─── Auth storage keys ─── */
export const ACCESS_TOKEN_KEY = "scp_access_token";
export const REFRESH_TOKEN_KEY = "scp_refresh_token";
